#前台应用server
#1.使用feign作为服务调用
#2.使用feign自带hystrix断路由

server:
  port: 8020
app:
spring:
  application:
    name: app-client
  profiles:
    #取值:server,dev,prod
    active: server,dev
  jpa:
    # 不让jap打印sql日志，让log4j2来打印
#    show-sql: true
    properties:
      hibernate:
        format_sql: true

  #    hibernate:
  #      ddl-auto: update
  #  jooq:
  #    sql-dialect: org.hibernate.dialect.MySQLInnoDBDialect

  #热部署功能
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  datasource:
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      log-abandoned: true
      #对于长时间不使用的连接强制关闭
      remove-abandoned: true
      #数据库链接超过3分钟开始关闭空闲连接 秒为单位
      remove-abandoned-timeout: 180
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
        # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow: 127.0.0.1
        # IP黑名单 (存在共同时，deny优先于allow)
        deny: 192.168.1.73
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: admin
        # 登录密码
        login-password: 123456




eureka:
  client:
    service-url:
      #指定服务注册中心的地址
      defaultZone: http://127.0.0.1:2001/eureka/,http://127.0.0.1:2002/eureka/
  instance:
    #每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
    lease-renewal-interval-in-seconds: 1
    #告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
    lease-expiration-duration-in-seconds: 2
hystrix:
  metrics:
    #feign自带断路器，默认true
    enabled: true
  command:
    default:
      execution:
        isolation:
          # 转发 header 需要定义这个。否则调用远程服务失败。
          strategy: SEMAPHORE
          thread:
            # 远程调用超时时间。
            timeoutInMilliseconds: 10000

# 调用其他服务时，开启自定义异常处理。
feign:
  hystrix:
    enabled: true

# 配置远程调用超时时间时，需要配置：ReadTimeout，SocketTimeout。
ribbon:
  ReadTimeout: 60000  # 单位毫秒数
  SocketTimeout: 60000
